name: Update Filter Lists

on:
  schedule:
    - cron: "0 21 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_ENV: production

jobs:
  cgps:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install npm dependencies
        run: npm ci

      - name: Download recommended whitelist
        run: bash ./get_recommended_whitelist.sh
        env:
          ALLOWLIST_URLS: ${{ vars.ALLOWLIST_URLS }}

      - name: Download recommended filters
        run: bash ./get_recommended_filters.sh
        env:
          BLOCKLIST_URLS: ${{ vars.BLOCKLIST_URLS }}
      - name: Generate
        run: |
          echo "Temp" >> ./temp.txt
      - name: Keep
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: keep
          skip_checkout: true
          skip_dirty_check: true
          push_options: '--force'
          file_pattern: ./temp.txt
          commit_message: Bump
        
      - name: Send ping request
        if: env.PING_URL != ''
        run: |
          curl "${{ env.PING_URL }}"
        env:
          PING_URL: ${{ secrets.PING_URL }}
